### ISSUE TITLE
Modifications to codebase

### ISSUE THREAD

**Issue by prasadtalasila** [DeveloperCAP/SCAT#38]
Modifications:

1. Usage tutorial wiki page
1. driver file with path import
1. correct the data directory path in config.py

**Comment by hrishikesh-dahiya** [comment]
the import is not needed in the driver file as it is already on the top level

**Comment by hrishikesh-dahiya** [comment]
https://github.com/DeveloperCAP/SCAT/wiki/How-To-Use-SCAT
The wiki page is created. Please review

**Comment by prasadtalasila** [comment]
The wiki page looks good.

**Comment by prasadtalasila** [comment]
@hrishikesh-dahiya is the data/ path to which the json files are stored changed?

**Comment by hrishikesh-dahiya** [comment]
in the config.py, yes, now it stores it in root directory, you can verify in the PR

**Comment by prasadtalasila** [comment]
PR #39 solves the issue.
